name: Android Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-36
            build-tools;36.0.0

      - name: Create local.properties (optional)
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Run lint
        run: ./gradlew lint
