name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INCLUDE_ANDROID: true
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g -XX:+UseParallelGC'"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Install Android commandline-tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o clt.zip
          mkdir -p cmdline-tools
          unzip -q clt.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Install required SDK packages
        run: |
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platforms;android-36" \
            "build-tools;36.0.0" \
            "platform-tools"

      - name: Create local.properties (sdk.dir)
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Lint
        run: ./gradlew --no-daemon lint

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Unit tests
        run: ./gradlew --no-daemon testDebugUnitTest

      # Upload doar pe push in main (eviti quota pe PR-uri)
      - name: Upload Debug APK
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          retention-days: 3

      # Release semnat (optional – ruleaza doar daca ai secrets/keystore)
      # - name: Build Release APK
      #   if: ${{ env.SIGNING_ENABLED == 'true' }}
      #   env:
      #     SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      #     SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      #     SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      #   run: ./gradlew --no-daemon assembleRelease

      # - name: Upload Release APK (optional)
      #   if: ${{ env.SIGNING_ENABLED == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-${{ github.run_number }}
      #     path: app/build/outputs/apk/release/*.apk
      #     if-no-files-found: ignore
      #     retention-days: 3
