name: Android Lint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Run Lint
        run: ./gradlew --no-daemon --stacktrace lint

      - name: Show Lint reports (paths)
        if: always()
        run: |
          echo "== Lint outputs =="
          find . -type f -path "*/build/reports/lint/*" -print || true